In [2]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
cd /content/drive/MyDrive/Github/nlpstudy

/content/drive/MyDrive/Github/nlpstudy


In [10]:
!git config --global user.email "dlxogn12345@gmail.com"
!git config --global user.name "Taewhoo"

In [18]:
!git remote add origin https://Taewhoo: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@github.com/Taewhoo/nlpstudy

In [33]:
!cp ./* ../nlpstudy2

머신러닝

1. 수집: 자연어(텍스트) 데이터를 코퍼스(corpus)라고 부른다.

2. 점검 및 탐색: 탐색적 데이터 분석(EDA) 단계라고도 한다. cf) pandas_profiling

3. 전처리 및 정제 (다양한 라이브러리)

4. 모델링 및 훈련: 선형 회귀, 소프트맥스 회귀 등 모델 선정 후 전처리된 데이터로 훈련. 이때 일부는 검증용, 테스트용으로 남겨두고 훈련용 데이터만 사용

5. 평가: 테스트용 데이터로 성능 평가

6. 배포




(1)토큰화: corpus(말뭉치) -> token

기준이 단어라면, 단어 토큰화. 단 여기에는 단어구, 의미를 갖는 문자열 등도 포함됨

NLTK: 영어 코퍼스를 토큰화하는 도구 제공

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

1. 단어 토큰화

In [ ]:
from nltk.tokenize import word_tokenize
print(word_tokenize("Don't be fooled by Mr. Jone's dark, sounding name."))
# word_tokenize : don't -> do / n't, Jone's -> Jone, 's

['Do', "n't", 'be', 'fooled', 'by', 'Mr.', 'Jone', "'s", 'dark', ',', 'sounding', 'name', '.']


In [ ]:
from nltk.tokenize import WordPunctTokenizer # punctuation marks - 구두점
print(WordPunctTokenizer().tokenize("Don't be fooled by Mr. Jone's dark, sounding name."))
# WordPunctTokenizer : don't -> don, ' , t (구두점 및 아포스트로피 별도 분류)

['Don', "'", 't', 'be', 'fooled', 'by', 'Mr', '.', 'Jone', "'", 's', 'dark', ',', 'sounding', 'name', '.']


In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print(text_to_word_sequence("Don't be fooled by Mr. Jone's dark, sounding name."))
# tensorflow의 케라스는 모든 알파벳을 소문자로, 구두점은 버림, 아포스트로피는 붙임

["don't", 'be', 'fooled', 'by', 'mr', "jone's", 'dark', 'sounding', 'name']


주의사항

1. 구두점, 특수문자 단순제외하면 안됨
  
  문장경계 파악에 도움될수도 있고, 단어 자체에
  구두점 있는 경우도 있다. 가격($) 등도 있다.

2. 줄임말, 단어 내 띄어쓰기
  
  we're(we are) : "re"를 접어(clitic)이라고 한다.
  New York : 하나의 단어로 인식되어야

Penn-Treebank Tokenization
1. hyphen words = 1 word
2. apostrophe + clitic = 2 words

In [ ]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
text = """Starting a home-based restaurant may be an ideal.
it doesn't have a food chain or restaurant of their own."""
print(tokenizer.tokenize(text))

#home-based : 1 word
#doesn't : 2 words (does, n't)

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


2. 문장 토큰화

역시 문장 구분자로 구분하는게 정답은 아니다.

ex. gmail.com, Ph.D.

문장 토큰화에는 sent_tokenize를 사용한다.

In [ ]:
from nltk.tokenize import sent_tokenize
text = """His barber kept his word.
But keeping such a huge secret to himself was driving him crazy.
Finally, the barber went up a mountain and almost to the edge of a cliff.
He dug a hole in the midst of some reeds.
He looked about, to make sure no one was near."""

print(sent_tokenize(text))

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [ ]:
#문장 중간 마침표 등장?
text2 = """I am actively looking for Ph.D. students.
and you are a Ph.D student."""

print(sent_tokenize(text2))

# sent_tokenize: 단순히 문장 구분자로 문장을 구분하지 않는다!

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [ ]:
pip install kss

     |████████████████████████████████| 42.4 MB 1.3 MB/s 
     |████████████████████████████████| 174 kB 49.2 MB/s 
  Created wheel for kss: filename=kss-3.3.1.1-py3-none-any.whl size=42449241 sha256=c23cb019680eba044fde2ac94730e98fa6653ead22c023f0602faad2f93a6d0a
  Stored in directory: /root/.cache/pip/wheels/6e/9d/1d/52871154eff5273abb86b96f4f984c1cd67c5bde64239b060a
  Created wheel for emoji: filename=emoji-1.6.3-py3-none-any.whl size=170298 sha256=872dc2d78c583606d7ce645f56f85b85153060835f7bd30b1a82c462c2ce0c39
  Stored in directory: /root/.cache/pip/wheels/03/8b/d7/ad579fbef83c287215c0caab60fb0ae0f30c4d7ce5f580eade
Successfully built kss emoji


In [ ]:
#한국어: kss (Korean Sentence Splitter)
import kss
text = """딥 러닝 자연어 처리가 재밌기는 합니다.
그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.
이제 해보면 알걸요?"""

print(kss.split_sentences(text))

[Korean Sentence Splitter]: Initializing Pynori...


['딥 러닝 자연어 처리가 재밌기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.', '이제 해보면 알걸요?']


한국어 토큰화의 어려움 : 교착어라는 점에서 기인함 (조사, 어미 등이 붙는 단어)

조사는 분리해줘야 하므로 공백문자 분리로는 부족함.

형태소: 뜻을 가진 가장 작은 단위

자립형태소: 명사,대명사,수사,관형사,부사
의존형태소: 접사,어미,조사,어간


ex. 에디가 딥러닝책을 읽었다

-> 에디, 딥러닝책 (자립)
가, 을, 읽, 었, 다 (의존)

즉 영어의 단어 토큰화는 한국어의 형태소 토큰화와 유사하다. (어절 토큰화 x)

추가로 띄어쓰기가 잘 지켜지지 않는다.
띄어쓰기 없어도 이해가 잘되는 언어이기 때문

In [ ]:
# 품사 태깅 (part-of-speech tagging)
from nltk.tokenize import word_tokenize
text = """I am actively looking for Ph.D. students.
and you are a Ph.D. student."""
print(word_tokenize(text))

['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']


In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
from nltk.tag import pos_tag #part-of-speech tagging
result = word_tokenize(text)
print(pos_tag(result))

[('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


PRP: 인칭대명사

VBP: 동사

RB: 부사

VBG: 현재분사

IN: 전치사

NNP: 고유명사

NNS: 복수명사

CC: 접속사

DT: 관사


In [ ]:
%%bash
apt-get update
apt-get install g++ openjdk-8-jdk python-dev python3-dev
pip3 install JPype1
pip3 install konlpy

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:4 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Hit:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Hit:11 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backpor

In [ ]:
# konlpy (korea nl python), Okt (Open korea text)
from konlpy.tag import Okt
okt = Okt()
print(okt.morphs("열심히 코딩한 당신, 연휴에는 여행을"))

['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을']


In [ ]:
print(okt.nouns("열심히 코딩한 당신, 연휴에는 여행을")) #명사 추출

['코딩', '당신', '연휴', '여행']


In [ ]:
# 꼬꼬마 형태소 분석기
from konlpy.tag import Kkma
kkma = Kkma()
print(kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을"))

['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을']


(2) 정제, 정규화

정제: 코퍼스로부터 노이즈 데이터 제거

정규화: 표현 방법이 다른 단어들을 통합시킴



1. 표기가 다른 단어들의 통합

ex. USA = US, uh-huh = uhhuh (정규화 가능)

2. 대,소문자 통합
: 대부분 대문자 -> 소문자 (문장앞 제외 보통 소문자기 때문)

ex. automobile 찾으면 Automobile까지 검색

다만 무작정은 안됨. US는 us와 구별되어야.

회사이름(General Motors), 사람이름(Bush) 구별되어야.



3. 노이즈 데이터(불필요한 단어) 제거

불용어, 빈도 적은 단어, 길이 짧은 단어 제거 등

- 빈도 적은 단어

ex. 100,000개 단어 중, 정상/스팸 메일에 주로 등장하는 단어 구분할 때

총 5번만 나오는 단어는 도움 안됨

- 길이 짧은 단어

영어는 한국어와 다르게 평균 단어 길이가 6~7.

2~3 이하인 단어만 없애도 의미없는 단어 없앨 수 있음.

ex. 관사(a), 주어(I), it/at/on/in...(불용어), 구두점까지



In [ ]:
import re
text = "I was wondering if anyone out there could enlighten me on this car."
shortword = re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('',text)) #compile 해당되는부분을 ''로 변경.

 was wondering anyone out there could enlighten this car.


(3) 표제어 추출, 어간 추출

-표제어 추출(lemmatization)

뿌리 단어를 찾아 다른 형태의 단어들을 합치는 것

ex. am, are, is -> be (표제어)

표제어 추출 위해서는 형태학적 분석(parsing) 먼저 진행해야.


---


어간(stem): 단어 의미 담는 핵심 부분 (cat)

접사(affix): 단어 추가적 의미 부분 (s)


어간 추출과는 달리, 표제어 추출은 해당 단어의 품사 정보를 보존한다. (POS 태그 보존)


In [ ]:
import nltk
nltk.download('wordnet') #표제어 추출 도구

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([lemmatizer.lemmatize(w) for w in words])

['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [ ]:
lemmatizer.lemmatize('doing', 'v')
# 표제어 추출기는 단어의 품사 정보를 알아야만 정확히 나온다.

'do'

In [ ]:
lemmatizer.lemmatize('dies', 'v')

'die'

In [ ]:
# 어간추출 (stemming) : 규칙만 놓고 단어의 어미를 자름. 어림짐작의 작업!
# PorterStemmer 주로 사용
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer = PorterStemmer()
text = """This was not the map we found in Billy Bones's chest,
but an accurate copy, complete in all things--
names and heights and soundings--
with the single exception of the red crosses and the written notes."""

words = word_tokenize(text)
print(words)

['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']


In [ ]:
print([stemmer.stem(w) for w in words])

['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [ ]:
# -alize = -al , -ance = 제거

words = ['formalize', 'allowance', 'electrical']
print([stemmer.stem(w) for w in words])

['formal', 'allow', 'electr']


In [ ]:
stemmer.stem('the going')

'the go'

In [ ]:
lemmatizer.lemmatize('the going')

'the going'

한국어 어간 추출

체언) 명사, 대명사, 수사

수식언) 관형사, 부사

관계언) 조사

독립언) 감탄사

용언) 동사, 형용사 : 어간, 어미의 결합으로 구성



ex. 긋다, 긋고, 그어서, 그어라

어간: 용언에서 변하지 않는(때때로 변하지만) 부분 '긋'

어미: 용언의 어간 뒤 붙어서 변하는 부분.

규칙활용: 어간의 모습이 일정.

불규칙활용: 어간이 바뀌거나 특수한 어미를 취함

ex. 듣-들, 돕-도우, 잇-이 등

오르 + 어 = 올라, 이르 + 어 = 이르러 등

불규칙 활용은 단순 분리를 넘어서 더욱 복잡한 규칙 요구됨.


(4) 불용어: 분석 의미가 적은 단어들

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')[:10]

# nltk가 정의한 불용어 리스트 (english)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

example = "Family is not an important thing."
stop_words = set(stopwords.words('english'))

tokens = word_tokenize(example)

result = []
for w in tokens:
  if w not in stop_words:
    result.append(w)

print(tokens)
print(result)

['Family', 'is', 'not', 'an', 'important', 'thing', '.']
['Family', 'important', 'thing', '.']


In [ ]:
#한국어 불용어 제거 (직접지정)

In [ ]:
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt
okt = Okt()
example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든."

stop_words = "를 고 게 때 아무렇게나"

stop_words = set(stop_words.split())
tokens = okt.morphs(example)

result = [w for w in tokens if w not in stop_words]

print(tokens)
print(result)

['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.']
['고기', '구', '우려', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '아니거든', '.']


(5) 정규 표현식

In [ ]:
#re.sub : 영어 텍스트 내 특수문자 제거 등에 용이

text = """Regular expression : A regular expression,
regex or regexp[1] (sometimes called a rational expression)
[2][3] is, in theoretical computer science and formal language
 theory, a sequence of characters that define a search pattern."""

import re
re.sub('[^a-zA-Z]', ' ', text)

'Regular expression   A regular expression   regex or regexp     sometimes called a rational expression         is  in theoretical computer science and formal language  theory  a sequence of characters that define a search pattern '

In [ ]:
text = """100 John    PROF
101 James   STUD
102 Mac   STUD"""

re.split('\s+', text)

['100', 'John', 'PROF', '101', 'James', 'STUD', '102', 'Mac', 'STUD']

In [ ]:
re.findall('\d+', text)

['100', '101', '102']

In [ ]:
re.findall('[A-Z]{4}', text)

['PROF', 'STUD', 'STUD']

In [ ]:
re.findall('[A-Z][a-z]+', text)

['John', 'James', 'Mac']

In [ ]:
#정규표현 이용한 토큰화 (Regexp Tokenizer)
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('\w+') #단어로 추출
print(tokenizer.tokenize("Don't be fooled by the dark sounding name"))

['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name']


In [ ]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('\s+', gaps=True) # 정규표현식을 구분자로 이용
# 공백으로 추출이 아닌, 공백으로 분리
print(tokenizer.tokenize("Don't be fooled by the dark sounding name"))

["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name']


(6) 정수 인코딩: 각 단어를 고유한 정수에 맵핑시킨다.

컴퓨터는 텍스트보다 숫자를 더 잘 처리한다.

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# dictionary 사용
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
raw_text = """A barber is a person. a barber is good person.
a barber is huge person. he Knew A Secret!
The Secret He Kept is huge secret. Huge secret.
His barber kept his word. a barber kept his word.
His barber kept his secret. But keeping and keeping
such a huge secret to himself was driving the barber crazy.
the barber went up a huge mountain."""

In [ ]:
sentences = sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping \nsuch a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sent in sentences: #각문장
  word = word_tokenize(sent) #각문장 내 단어들

  result = []
  for w in word: #각 단어
    w = w.lower() #단어 소문자화
    if w not in stop_words: #불용어 제거
      if len(w) > 2: # 단어 길이 제어
        result.append(w)
        if w not in vocab:
          vocab[w] = 0
        vocab[w] += 1        # 단어별 빈도수
  preprocessed_sentences.append(result)
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [ ]:
vocab_sort = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sort)
# counter를 사용하는 것이 더욱 편리하다.

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [ ]:
# 빈도수 순위로 다르게 표현
word_rank = {}
i = 0
for (word, frequency) in vocab_sort:
  if frequency > 1: # 빈도수 적은 단어 제외
    i = i + 1
    word_rank[word] = i # {word, i} 구조 확립

print(word_rank)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [ ]:
# 상위 5개만 추출
vocab_size = 5
low_ranked_words = [word for word, rank in word_rank.items() if rank > vocab_size]
for w in low_ranked_words:
  del word_rank[w]  #word_rank dictionary에서 w에 해당하는 인덱스 정보 삭제
print(word_rank)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
preprocessed_sentences
# 2번째 문장의 'good'은 word_rank에 존재하지 않는다. -> OOV (out-of-vocabulary)

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [ ]:
word_rank['OOV'] = len(word_rank) + 1
print(word_rank)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [ ]:
#정수 인코딩
encoded_sentences = []
for wordlist in preprocessed_sentences:
  encoded_sentence = []
  for word in wordlist:
    try:
      encoded_sentence.append(word_rank[word]) #word rank 단어의 index 추가
    except KeyError:
      encoded_sentence.append(word_rank['OOV'])
  encoded_sentences.append(encoded_sentence)
print(encoded_sentences)



[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [ ]:
# 정수 인코딩 - Counter 사용
from collections import Counter
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
wordlist = sum(preprocessed_sentences, [])
print(wordlist)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [ ]:
# counter: 중복 제거, 빈도수 카운트
vocab = Counter(wordlist)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [ ]:
print(vocab['barber'])

8


In [ ]:
vocab = vocab.most_common(5)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
word_rank = {}
i = 0
for (word, frequency) in vocab:
  i = i + 1
  word_rank[word] = i

print(word_rank)


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
# 정수 인코딩 - nltk의 'FreqDist' 사용하기

from nltk import FreqDist # FreqDist : 리스트 내 단어와 반복횟수를 묶어서 출력
import numpy as np
print(np.hstack(preprocessed_sentences), '\n')
vocab = FreqDist(np.hstack(preprocessed_sentences))
# np.hstack: 문장 구분을 모두 제거 ([], ',')
vocab

['barber' 'person' 'barber' 'good' 'person' 'barber' 'huge' 'person'
 'knew' 'secret' 'secret' 'kept' 'huge' 'secret' 'huge' 'secret' 'barber'
 'kept' 'word' 'barber' 'kept' 'word' 'barber' 'kept' 'secret' 'keeping'
 'keeping' 'huge' 'secret' 'driving' 'barber' 'crazy' 'barber' 'went'
 'huge' 'mountain'] 



FreqDist({'barber': 8,
          'crazy': 1,
          'driving': 1,
          'good': 1,
          'huge': 5,
          'keeping': 2,
          'kept': 4,
          'knew': 1,
          'mountain': 1,
          'person': 3,
          'secret': 6,
          'went': 1,
          'word': 2})

In [ ]:
vocab = vocab.most_common(5)
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [ ]:
word_rank = {word[0] : index + 1 for index, word in enumerate(vocab)}
# enumerate: 몇번째 for 구문인지 같이 출력. ex) (0,1), (1,5), (2,8, ....
word_rank

{'barber': 1, 'huge': 3, 'kept': 4, 'person': 5, 'secret': 2}

케라스(Keras)의 텍스트 전처리

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
preprocessed_sentences # 문장별 토큰화는 진행해주고 시작해야 한다.

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
# fit_on_texts : 단어 빈도수로 순위 정렬 (word_index 사용해 결과확인)
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [ ]:
tokenizer.texts_to_sequences(preprocessed_sentences)
# texts_to_sequences : 전처리된 단어들을 정수 인코딩

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [ ]:
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 1)
# num_words : 빈도수 상위 몇개만 사용할지 정할 수 있다.
tokenizer.fit_on_texts(preprocessed_sentences)
print(tokenizer.word_index)
# 정수 인코딩된 경우, word_index로 확인 불가

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [ ]:
# OOV 보존
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 2, oov_token = 'OOV')
# 0, OOV 고려해서 num_words = 7
tokenizer.fit_on_texts(preprocessed_sentences)
print('OOV의 인덱스 : {}'.format(tokenizer.word_index['OOV']))

OOV의 인덱스 : 1


In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


패딩 (Padding, zero padding)

문장별로 길이를 동일하게 맞춰주는 것

기계는 길이가 동일한 문서들을 하나의 행렬로 병렬 연산이 가능하므로

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
# 괄호 안 텍스트의 단어들을 빈도수에 따라 집합 생성

In [ ]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
max_len = max(len(item) for item in encoded)
print(max_len) #길이가 가장 긴 문장의 길이

7


In [ ]:
for sentences in encoded:
  while len(sentences) < max_len:
    sentences.append(0)

padded_np = np.array(encoded)
padded_np

#문장별로 최대길이가 될 때까지 0으로 채움
#기계는 이를 하나의 행렬로 인식, 병렬처리 가능(0번 단어는 무시된다.)

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [ ]:
# 모듈을 사용한다면
from tensorflow.keras.preprocessing.sequence import pad_sequences
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
padded = pad_sequences(encoded) #인코딩된 리스트에 pad_sequences 적용
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [ ]:
padded = pad_sequences(encoded, padding = 'post')
padded

# padding = 'post' 추가 시 0을 뒤에서부터 채운다.
# 주로 앞에 0을 붙이는 편. X - y 데이터 구분 시 출력값에 0이 많으면 안좋으므로

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [ ]:
# 꼭 최대길이 문서에만 맞출 필요는 없고, 0 아닌 다른 숫자로 채울 수 있다.
padded = pad_sequences(encoded, padding = 'post', maxlen = 5, value = 14)
padded

array([[ 1,  5, 14, 14, 14],
       [ 1,  8,  5, 14, 14],
       [ 1,  3,  5, 14, 14],
       [ 9,  2, 14, 14, 14],
       [ 2,  4,  3,  2, 14],
       [ 3,  2, 14, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  2, 14, 14],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14]], dtype=int32)

원-핫 인코딩

단어 집합: 중복되지 않는 단어들의 모음

단어 집합의 크기 = 벡터로 표현.

표현하고 싶은 단어의 인덱스 = 1, 나머지는 0

이렇게 표현된 벡터를 원-핫 벡터라고 한다.


---


(1) 고유 인덱스 부여 (정수 인코딩)

(2) 표현하고 싶은 단어의 인덱스 = 1, 다른 단어에는 0 부여

In [ ]:
# example

#토큰화
from konlpy.tag import Okt
okt = Okt()
token = okt.morphs("나는 자연어 처리를 배운다")
print(token)

['나', '는', '자연어', '처리', '를', '배운다']


In [ ]:
word2index = {}
for voca in token:
  if voca not in word2index.keys():
    word2index[voca] = len(word2index) #0부터 시작해서 인덱스 배정
print(word2index)

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [ ]:
def one_hot_encoding(word, word2index):
  one_hot_vector = [0]*(len(word2index)) # [0,0,0,0,0,0]
  index = word2index[word] #인덱스 = 문장 내 단어 순서
  one_hot_vector[index] = 1 # [0,0,1,0,0,0]
  return one_hot_vector

one_hot_encoding('자연어', word2index)

[0, 0, 1, 0, 0, 0]

In [ ]:
[0]*6

[0, 0, 0, 0, 0, 0]

In [ ]:
# 케라스 활용
text = '나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야'
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text]) # 리스트로 묶지 않으면 글자 하나하나의 빈도수를 센다.
print(tokenizer.word_index)

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [ ]:
encoded = tokenizer.texts_to_sequences([text])
print(encoded)
# 빈도수 순으로 정렬 후 texts_to_sequences

[[4, 2, 5, 1, 2, 6, 3, 1, 1, 3, 7]]


In [ ]:
one_hot = to_categorical(encoded)
print(one_hot)

#한계 : 저장공간 측면에서 비효율적, 단어의 유사도 표현 불가 (ex.연관 검색어를 보여줄 수 없다.)

[[[0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]]]


데이터의 분리 : 머신 러닝을 위해서는 데이터를 적절히 분리해야 한다.

지도 학습

데이터는 총 4개로 나뉨.

X_train: 학습용 데이터 (18000개)

y_train: 학습용 정답 데이터 (18000개)

X_test: 시험용 데이터 (2000개)

y_test: 시험지 정답 데이터 (2000개)

X, Y 분리하기

In [ ]:
# zip 함수 : [문제, 정답] -> (문제끼리), (정답끼리)
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [ ]:
sequences = [['a',1], ['b',2], ['c',3]]
X, y = zip(*sequences) # *: '추가'
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [ ]:
#데이터프레임 이용 분리
import pandas as pd
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]

columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [ ]:
X = df['메일 본문']
y = df['스팸 메일 유무']

print(X)
print(y)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object
0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


In [ ]:
# Numpy 활용
import numpy as np

np_array = np.arange(0,16).reshape(4,4)
print(np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
X = np_array[:, :3] #행은 전체, 열은 3열까지
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [ ]:
y = np_array[:,3]
print(y)

[ 3  7 11 15]


테스트 데이터 분리하기

In [ ]:
# 사이킷 런
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape(5,2), range(5)

print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [ ]:
# 3분의 1만 test data 지정
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)
print("train data:\n",X_train)
print("test data:\n", X_test)
# random_state 숫자에 따라서 다른 순서로 데이터가 섞인다. 즉 동일 코드를 재현하고자 한다면 값을 고정해주면 된다.

train data:
 [[2 3]
 [4 5]
 [6 7]]
test data:
 [[8 9]
 [0 1]]


In [ ]:
# 수동으로 분리
import numpy as np
X,y = np.arange(0,24).reshape(12,2), range(12)
print(X)
print(list(y))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
num_of_train = int(len(X) * 0.8) #전체 데이터의 80%
num_of_test = int(len(X) - num_of_train) # 0.2를 곱하면, 소수점 아래로는 버려짐!!
print(num_of_train)
print(num_of_test)

9
3


In [ ]:
X_train = X[:num_of_train]
X_test = X[num_of_train:]
print(X_test) # 데이터가 섞이지 않은 채로 분리되므로, 분리 전 수동으로 데이터를 섞어줘야 한다.

[[18 19]
 [20 21]
 [22 23]]


한국어 전처리 패키지

Konlpy , kss(korean sentence splitter)와 함께 사용 가능

In [ ]:
# pykospacing : 띄어쓰기가 안된 문장을 처리해줌

!pip install git+https://github.com/haven-jeon/PyKoSpacing.git


  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-hgjls8_e
  Running command git clone -q https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-hgjls8_e
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)


In [ ]:
sent = """김철수는극중두인격의사나이이광수역을맡았다.
철수는한국유일의태권도전승자를가리는결전의날을앞두고
10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다."""

from pykospacing import Spacing
spacing = Spacing()
new_sent = spacing(sent)
print(new_sent)

김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.


In [ ]:
# Py-Hanspell : 맞춤법, 띄어쓰기 수정

!pip install git+https://github.com/ssut/py-hanspell.git


  Cloning https://github.com/ssut/py-hanspell.git to /tmp/pip-req-build-tyofbb7x
  Running command git clone -q https://github.com/ssut/py-hanspell.git /tmp/pip-req-build-tyofbb7x
  Created wheel for py-hanspell: filename=py_hanspell-1.1-py3-none-any.whl size=4868 sha256=6957b90ecdf2e923767eabb94f25832558d8aabd686e690023a09b5db4f52929
  Stored in directory: /tmp/pip-ephem-wheel-cache-_839oad_/wheels/ab/f5/7b/d4124bb329c905301baed80e2ae45aa14e824f62ebc3ec2cc4
Successfully built py-hanspell


In [ ]:
from hanspell import spell_checker
sent = "맞춤법 틀리면 외않되?"
correction = spell_checker.check(sent) #check - 체크만!

print(correction)

new_sent = correction.checked # checked - 체크된 내용 수정해서 반환
print(new_sent)

Checked(result=True, original='맞춤법 틀리면 외않되?', checked='맞춤법 틀리면 왜 안돼?', errors=1, words=OrderedDict([('맞춤법', 0), ('틀리면', 0), ('왜', 1), ('안돼?', 1)]), time=0.27916622161865234)
맞춤법 틀리면 왜 안돼?


In [ ]:
# soynlp - 기존 형태소 분석기의 문제점들 보완

# 신조어문제 : 문맥상 자주 연결될 경우, 단어 앞뒤 독립 단어들이 계속 등장할 경우를 고려함
from konlpy.tag import Okt
tokenizer = Okt()
print(tokenizer.morphs('에이비식스 이대휘 1월 최애돌')) # 에이비식스, 이대휘, 최애돌 분리됨


['에이', '비식스', '이대', '휘', '1월', '최애', '돌']


In [ ]:
!pip install soynlp

     |████████████████████████████████| 416 kB 14.8 MB/s 


In [ ]:
import urllib.request
from soynlp import DoublespaceLineCorpus
from soynlp.word import WordExtractor

#학습 기반이므로 데이터 다운로드
urllib.request.urlretrieve("https://raw.githubusercontent.com/lovit/soynlp/master/tutorials/2016-10-20.txt", filename="2016-10-20.txt")

('2016-10-20.txt', <http.client.HTTPMessage at 0x7f35d8777dd0>)

In [ ]:
corpus = DoublespaceLineCorpus('2016-10-20.txt') # 다수의 문서로 데이터 분리
len(corpus)

30091

In [ ]:
# 3개 문서만 출력
i = 0
for document in corpus:
  if len(document) > 0:
    print(document)
    i = i + 1
  if i == 3:
    break

19  1990  52 1 22
오패산터널 총격전 용의자 검거 서울 연합뉴스 경찰 관계자들이 19일 오후 서울 강북구 오패산 터널 인근에서 사제 총기를 발사해 경찰을 살해한 용의자 성모씨를 검거하고 있다 성씨는 검거 당시 서바이벌 게임에서 쓰는 방탄조끼에 헬멧까지 착용한 상태였다 독자제공 영상 캡처 연합뉴스  서울 연합뉴스 김은경 기자 사제 총기로 경찰을 살해한 범인 성모 46 씨는 주도면밀했다  경찰에 따르면 성씨는 19일 오후 강북경찰서 인근 부동산 업소 밖에서 부동산업자 이모 67 씨가 나오기를 기다렸다 이씨와는 평소에도 말다툼을 자주 한 것으로 알려졌다  이씨가 나와 걷기 시작하자 성씨는 따라가면서 미리 준비해온 사제 총기를 이씨에게 발사했다 총알이 빗나가면서 이씨는 도망갔다 그 빗나간 총알은 지나가던 행인 71 씨의 배를 스쳤다  성씨는 강북서 인근 치킨집까지 이씨 뒤를 쫓으며 실랑이하다 쓰러뜨린 후 총기와 함께 가져온 망치로 이씨 머리를 때렸다  이 과정에서 오후 6시 20분께 강북구 번동 길 위에서 사람들이 싸우고 있다 총소리가 났다 는 등의 신고가 여러건 들어왔다  5분 후에 성씨의 전자발찌가 훼손됐다는 신고가 보호관찰소 시스템을 통해 들어왔다 성범죄자로 전자발찌를 차고 있던 성씨는 부엌칼로 직접 자신의 발찌를 끊었다  용의자 소지 사제총기 2정 서울 연합뉴스 임헌정 기자 서울 시내에서 폭행 용의자가 현장 조사를 벌이던 경찰관에게 사제총기를 발사해 경찰관이 숨졌다 19일 오후 6시28분 강북구 번동에서 둔기로 맞았다 는 폭행 피해 신고가 접수돼 현장에서 조사하던 강북경찰서 번동파출소 소속 김모 54 경위가 폭행 용의자 성모 45 씨가 쏜 사제총기에 맞고 쓰러진 뒤 병원에 옮겨졌으나 숨졌다 사진은 용의자가 소지한 사제총기  신고를 받고 번동파출소에서 김창호 54 경위 등 경찰들이 오후 6시 29분께 현장으로 출동했다 성씨는 그사이 부동산 앞에 놓아뒀던 가방을 챙겨 오패산 쪽으로 도망간 후였다  김 경위는 오패산 터널 입구 오른쪽의 급경사에서 성씨에

In [ ]:
word_extractor = WordExtractor()
word_extractor.train(corpus)
score_table = word_extractor.extract()


training was done. used memory 2.291 Gb
all cohesion probabilities was computed. # words = 223348
all branching entropies was computed # words = 361598
all accessor variety was computed # words = 361598


soynlp의 응집확률: 높을수록 그 문자열이 하나의 단어로 등장할 가능성이 높아진다.


In [ ]:
score_table['반포한'].cohesion_forward

0.08838002913645132

In [ ]:
score_table['반포한강'].cohesion_forward

0.19841268168224552

In [ ]:
score_table['반포한강공'].cohesion_forward

0.2972877884078849

In [ ]:
score_table['반포한강공원'].cohesion_forward

0.37891487632839754

In [ ]:
score_table['반포한강공원에'].cohesion_forward
# 조사가 붙으면 응집도가 더 낮아짐. '반포한강공원'을 하나의 단어로 판단하기에 가장 적합하다.

0.33492963377557666

soynlp - branching entropy

In [ ]:
# 문자열에서 다음 문자가 등장할 수 있는 정도를 나타낸다.
# ex. 디(?) -> 디스(..?) -> 디스플(아~) -> 디스플레이

In [ ]:
score_table['디스'].right_branching_entropy
# '디스' 뒤에는 다양한 문자가 올 수 있다.

1.6371694761537934

In [ ]:
score_table['디스플'].right_branching_entropy
# '디스플' 이후에는 '레'가 오는 것이 너무나도 명백하므로 0 반환.

-0.0

In [ ]:
score_table['디스플레이'].right_branching_entropy
# 단어가 끝나면 조사 등이 붙을 수 있으므로 값이 증가한다.

3.1400392861792916

LTokenizer: 점수가 가장 높은 L토큰(응집도가 큰, 즉 단어)을 기준으로 분리한다.

In [ ]:
from soynlp.tokenizer import LTokenizer
scores = {word: score.cohesion_forward for word, score in score_table.items()}
# score.cohesion_forward : 응집도
l_tokenizer = LTokenizer(scores = scores)
l_tokenizer.tokenize('국제사회와 우리의 노력들로 범죄를 척결하자', flatten = False)

[('국제사회', '와'), ('우리', '의'), ('노력', '들로'), ('범죄', '를'), ('척결', '하자')]

In [ ]:
# 최대 점수 tokenizer : 띄어쓰기 안된 문장에서, 점수가 높은대로 순차적으로 찾아냄.
from soynlp.tokenizer import MaxScoreTokenizer

maxscore_tokenizer = MaxScoreTokenizer(scores = scores)
maxscore_tokenizer.tokenize('국제사회와우리의노력들로범죄를척결하자')

['국제사회', '와', '우리', '의', '노력', '들로', '범죄', '를', '척결', '하자']

In [ ]:
# 반복문자 정제 (ex.ㅋㅋㅋㅋㅋ)

from soynlp.normalizer import *
print(emoticon_normalize('앜ㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠ', num_repeats = 2))

아ㅋㅋ영화존잼쓰ㅠㅠ


In [ ]:
print(repeat_normalize('우하하하하', num_repeats = 2))

우하하


In [ ]:
# konlpy 커스터마이징 (ex. '은경이' -> 분리하지 않도록)

!pip install customized_konlpy

     |████████████████████████████████| 881 kB 12.0 MB/s 


In [ ]:
from ckonlpy.tag import Twitter # Twitter = 형태소 분석기
twitter = Twitter()
twitter.morphs('은경이는 사무실로 갔습니다.')

/usr/local/lib/python3.7/dist-packages/konlpy/tag/_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


['은', '경이', '는', '사무실', '로', '갔습니다', '.']

In [ ]:
twitter.add_dictionary('은경이', 'Noun') # 사전 추가
twitter.morphs('은경이는 사무실로 갔습니다.')

['은경이', '는', '사무실', '로', '갔습니다', '.']

정제-토큰화-불용어 제거-단어사전생성, 정수 인코딩-패딩-벡터화(원핫 인코딩)-모델에 입력

단어사전에 pad, oov도 추가한다.